version: "3"
networks:
  etworkame:
    driver: bridge
    ipam:
      config:
        - subnet: 172.16.147.0/24
services:
  server:
    volumes: 
     - servervol:/server/serverdata
    build: server/
    command: python ./server.py
    networks:
      etworkame:
        ipv4_address: 172.16.147.100
    ports:
      - 1234:1234
  client:
    volumes: 
     - clientvol:/client/clientdata
    build: client/
    command: python ./client.py
    depends_on:
      - server
    networks:
      etworkame:
        ipv4_address: 172.16.147.99

volumes:
  servervol:
  clientvol: